# model
model_name: depth_anything_v2
encoder: vits

# data
dataset: c3vd
input_size: 336  # 518
train_batch_size: 24
val_batch_size: 24
num_workers: 24

# train
weight_decay: 1e-4
lr: 3e-5  # 其他层的lr
lr_backbone: 1e-4  # backbone的lr
lr_scheduler: step
lr_step_size: 4
lr_gamma: 0.975

# trainer
trainer:
    max_epochs: 300
    accelerator: gpu
    devices: 2  # 多卡训练时设置显卡数量
    benchmark: true
    strategy: ddp  # 如果多卡训练就要开
#    profiler: simple
    check_val_every_n_epoch: 2  # 每训练几轮验证一次
    precision: 32-true  # 32-true or 16-mixed 训练精度，16-mixed可以提速，如果loss出nan了就改32-true
#    limit_train_batches: 2
#    limit_test_batches: 0.0
    enable_progress_bar: true  # 开关进度条
    gradient_clip_val: 0.5
#    detect_anomaly: true
#    accumulate_grad_batches: 2
